### ISSUE TITLE
Using mock in subtests result in panic with no indication

### ISSUE THREAD

**Issue by Soulou** [golang/mock#106]
Using go 1.9

```
func TestFoo1(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	t.Run("test 1", func(t *testing.T) {
		m := NewMockType(ctrl)

		t.Run("sub test 1", func(t *testing.T) {
			m.EXPECT().Method1().Return(nil)
                        // ...
		})
    })
}
```

It results in

```
panic: test executed panic(nil) or runtime.Goexit

goroutine 156 [running]:
testing.tRunner.func1(0xc420382410)
	/opt/go/src/testing/testing.go:622 +0x29d
runtime.Goexit()
	/opt/go/src/runtime/panic.go:366 +0x153
testing.(*common).FailNow(0xc42029b930)
	/opt/go/src/testing/testing.go:486 +0x39
testing.(*common).Fatalf(0xc42029b930, 0xd9a3fe, 0x2e, 0xc4200f6fa0, 0x5, 0x5)
	/opt/go/src/testing/testing.go:530 +0x83
github.com/user/project/vendor/github.com/golang/mock/gomock.(*Controller).Call(0xc4202456c0, 0xd4f540, 0xc4203912e0, 0xd75c80, 0x8, 0xc420357fe0, 0x2, 0x2, 0x0, 0x0, ...)
	/home/leo/Projects/Go/src/github.com/user/project/vendor/github.com/golang/mock/gomock/controller.go:132 +0x585
```

I assume it's related to #51, but as the issue is tagged fixed and I'm using the master branch here, I've the feeling it's not really closed.

I've also commented #51 with a few details.

Thanks a lot for your future answers.

**Comment by Soulou** [comment]
Ok I close this, follow up in #51
