### ISSUE TITLE
Panic during varargs handling

### ISSUE THREAD

**Issue by aaronbee** [golang/mock#130]
After upgrading to the latest gomock HEAD our test hit a panic:

```
panic: reflect.Set: value of type *gen.Routes is not assignable to type grpc.CallOption

goroutine 7 [running]:
reflect.Value.assignTo(0x150e040, 0xc42005f680, 0x16, 0x1563786, 0xb, 0x14d2780, 0xc42017d400, 0x0, 0x1012e40, 0x10)
	/usr/local/Cellar/go/1.9.2/libexec/src/reflect/value.go:2192 +0x3a6
reflect.Value.Set(0x14d2780, 0xc42017d400, 0x194, 0x150e040, 0xc42005f680, 0x16)
	/usr/local/Cellar/go/1.9.2/libexec/src/reflect/value.go:1357 +0xa4
reflect.Append(0x1491760, 0xc420196000, 0x97, 0xc42004f678, 0x1, 0x1, 0x97, 0x10494ac, 0x17ca8d8)
	/usr/local/Cellar/go/1.9.2/libexec/src/reflect/value.go:1840 +0xdd
arista/vendor/github.com/golang/mock/gomock.(*Call).matches(0xc42008f130, 0xc420153fc0, 0x2, 0x2, 0x1, 0xc42018e028)
	/Users/aaronb/go/src/arista/vendor/github.com/golang/mock/gomock/call.go:354 +0xace
arista/vendor/github.com/golang/mock/gomock.callSet.FindMatch(0xc4201581e0, 0xc420158210, 0x15205c0, 0xc420045320, 0x1565ab0, 0x10, 0xc420153fc0, 0x2, 0x2, 0xc42001e000, ...)
	/Users/aaronb/go/src/arista/vendor/github.com/golang/mock/gomock/callset.go:73 +0x1cd
arista/vendor/github.com/golang/mock/gomock.(*Controller).Call.func1(0xc420152520, 0x15205c0, 0xc420045320, 0x1565ab0, 0x10, 0xc420153fc0, 0x2, 0x2, 0x0, 0x0, ...)
	/Users/aaronb/go/src/arista/vendor/github.com/golang/mock/gomock/controller.go:146 +0x10f
arista/vendor/github.com/golang/mock/gomock.(*Controller).Call(0xc420152520, 0x15205c0, 0xc420045320, 0x1565ab0, 0x10, 0xc420153fc0, 0x2, 0x2, 0x0, 0x0, ...)
	/Users/aaronb/go/src/arista/vendor/github.com/golang/mock/gomock/controller.go:165 +0xdc
```

This is the function signature that is being mocked:

`GetNotifications(ctx context.Context, in *Routes, opts ...grpc.CallOption)`

Note the last argument is a vararg `grpc.CallOption`, but the second-to-last argument is a `*gen.Routes`. The call to this mocked function doesn't pass in any `opts`. During `FindMatch` `matches` is expected to return an error on unmatched EXPECTS, but it panics instead.

I believe the fix is the added else clause below in `matches`:

```
if len(c.args) == len(args) {
	if m.Matches(args[i]) {
		// Got Foo(a, b, c) want Foo(matcherA, matcherB, gomock.Any())
		// Got Foo(a, b, c) want Foo(matcherA, matcherB, someSliceMatcher)
		// Got Foo(a, b, c) want Foo(matcherA, matcherB, matcherC)
		// Got Foo(a, b) want Foo(matcherA, matcherB)
		// Got Foo(a, b, c, d) want Foo(matcherA, matcherB, matcherC, matcherD)
		break
	} else { // MISSING ELSE CLAUSE
		return fmt.Errorf("Expected call at %s doesn't match the argument at index %s.\nGot: %v\nWant: %v",
			c.origin, strconv.Itoa(i), args[i], m)
	}
}
```

By adding the else branch we return from this code, before trying to cast `args[i]` into a `grpc.CallOption`.

**Comment by balshetzer** [comment]
Thanks for the report. Any chance you want to turn your code above into a pull request?
